version: '3.8'

networks:
  admin_network:
  rabbit_mq_network: 
    external: true
  

services:
  admin: 
    build: ./
    volumes:
      - .:/app
    ports: 
      - 8007:8000
    networks:
      - rabbit_mq_network
      - admin_network
    depends_on:
      - admin_db
  
  admin_db: 
    image: mysql
    restart: always
    expose:
      - 3306
    volumes:
      - admindb_vol:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - admin_network
    

volumes:
  admindb_vol: 